extends Node
## Plays sound effects from a small player pool and loops the music across scenes.
## Sounds are generated by tools/make_sounds.gd.

const SOUNDS := {
	"jump": preload("res://audio/jump.wav"),
	"slide": preload("res://audio/slide.wav"),
	"drop": preload("res://audio/drop.wav"),
	"hit": preload("res://audio/hit.wav"),
	"knockout": preload("res://audio/knockout.wav"),
	"combo": preload("res://audio/combo.wav"),
	"win": preload("res://audio/win.wav"),
	"lose": preload("res://audio/lose.wav"),
	"click": preload("res://audio/click.wav"),
}
const MUSIC := preload("res://audio/music.wav")
const POOL_SIZE := 8
const MUSIC_VOLUME_DB := -10.0

var _players: Array[AudioStreamPlayer] = []
var _next_player := 0
var _music: AudioStreamPlayer


func _ready() -> void:
	# Keep playing while the tree is paused or slowed down.
	process_mode = Node.PROCESS_MODE_ALWAYS
	for i in POOL_SIZE:
		var player := AudioStreamPlayer.new()
		add_child(player)
		_players.append(player)
	_music = AudioStreamPlayer.new()
	_music.stream = MUSIC
	_music.volume_db = MUSIC_VOLUME_DB
	add_child(_music)
	_music.play()


## Plays a named effect. pitch_spread randomizes the pitch a little so repeats sound alive.
func play(sound: String, pitch_spread := 0.0) -> void:
	var player := _players[_next_player]
	_next_player = (_next_player + 1) % _players.size()
	player.stream = SOUNDS[sound]
	player.pitch_scale = 1.0 + randf_range(-pitch_spread, pitch_spread)
	player.play()
